
import { downloadBlob, wrapHtml, copyText } from "@/lib/spec-download";

export const routeOptions = ({
  head: () => ({
    meta: [
      { title: "Folder Structure — Salon SaaS" },
      { name: "description", content: "Module layout and folder structure for the Salon SaaS codebase: routes, components, server functions, Prisma schema and conventions for where new code belongs." },
    ],
  }),
  component: FolderStructurePage,
});

const TREE = String.raw`salon-saas/
├── prisma/
│   ├── schema.prisma          # PostgreSQL — source of truth (mirrored on /schema)
│   └── migrations/            # Generated by supabase--migration; never hand-edit
├── specs/
│   ├── api-contract.md        # Mirrored on /api-contract
│   ├── auth-strategy.md       # Mirrored on /auth-strategy  (OAuth-only)
│   ├── offline-sync-strategy.md # SQLite mirror + push/pull + conflict rules
│   ├── claude.md              # Mirrored on /claude-md
│   ├── folder-structure.md    # Mirrored on /folder-structure
│   └── srs.md                 # Mirrored on /doc
├── electron/                  # Desktop POS app (online + offline)
│   ├── main.cjs               # BrowserWindow, IPC, app lifecycle
│   ├── preload.cjs            # contextBridge — exposes sync + sqlite APIs to renderer
│   ├── sqlite/
│   │   ├── schema.sql         # POS subset of Postgres (Order, Customer, Service, …)
│   │   ├── migrations/        # Versioned, applied on app start
│   │   └── repo.ts            # better-sqlite3 wrappers (typed queries)
│   ├── sync/
│   │   ├── pull-worker.ts     # polls /api/pos/sync/manifest + /pull
│   │   ├── push-worker.ts     # drains outbound queue → /api/pos/sync/push
│   │   └── conflict.ts        # resolution policy (server-wins / client-wins / ts-wins)
│   ├── keychain.ts            # OS keychain wrapper (keytar) for refresh token
│   └── packager.config.cjs    # @electron/packager config (win/mac/linux)
├── sockets/                   # Socket.IO server (runs alongside HTTP)
│   ├── server.ts              # io = new Server(httpServer, …)
│   ├── auth.ts                # JWT handshake check, joins company/branch/device rooms
│   ├── emit.ts                # typed helpers: emitOrderCreated, emitInventoryLow, …
│   └── events.ts              # zod schemas for every C→S and S→C event
├── src/
│   ├── routes/                # File-based routes (TanStack Router, flat dot-routing)
│   │   ├── __root.tsx
│   │   ├── index.tsx          # Marketing landing
│   │   ├── home.tsx
│   │   ├── pricing.tsx · about.tsx · blog.tsx · blog_.$slug.tsx
│   │   ├── doc.tsx · schema.tsx · theme.tsx
│   │   ├── api-contract.tsx · auth-strategy.tsx
│   │   ├── claude-md.tsx · folder-structure.tsx
│   │   ├── login.tsx          # OAuth-only: Google button + email-OTP form
│   │   ├── onboarding.tsx     # Post-first-OAuth wizard
│   │   ├── _authenticated.tsx
│   │   │
│   │   ├── admin.tsx + admin.*.tsx          # Platform admin
│   │   │   └── admin.invitations.tsx        # Invite Salon Owners (PENDING company)
│   │   ├── tenant.tsx + tenant.*.tsx        # Tenant portal
│   │   │   ├── tenant.invitations.tsx       # Owner invites staff (Manager/Cashier/Employee)
│   │   │   ├── tenant.products.tsx          # Saleable product catalog (inactive until purchased)
│   │   │   ├── tenant.product-categories.tsx
│   │   │   ├── tenant.product-purchases.tsx # Vendor purchase + branch distribution
│   │   │   ├── tenant.product-transfers.tsx # Branch-to-branch stock move (same batch)
│   │   │   ├── tenant.product-combos.tsx    # Bundle products as one POS line
│   │   │   └── tenant.products-revenue.tsx  # Branch × product profit (FIFO COGS)
│   │   ├── pos.tsx + pos_.*.tsx             # POS shell + sub-pages (web build)
│   │   │
│   │   └── api/
│   │       ├── chat.ts
│   │       └── public/
│   │           ├── feedback.ts
│   │           ├── webhooks/  # stripe, bkash, nagad, whatsapp …
│   │           └── cron/      # recompute-mrr, expire-trials, expire-loyalty …
│   │
│   ├── components/
│   │   ├── ui/                # shadcn primitives
│   │   ├── marketing/         # MarketingNav, hero blocks
│   │   ├── pos/               # POSShell, FloorCanvas, ManageShell, POSNav
│   │   │   └── OfflineBadge.tsx  # shows sync status (idle / syncing / offline)
│   │   ├── cms-crud.tsx · cms-fields.tsx · crud.tsx
│   │   ├── dashboard-layout.tsx
│   │   └── …
│   │
│   ├── lib/
│   │   ├── *.functions.ts     # TanStack server functions
│   │   ├── *.server.ts        # Server-only helpers
│   │   ├── *-store.ts         # Local stores (incl. invitations-store, products-store)
│   │   ├── *-context.tsx      # React context providers
│   │   ├── auth/
│   │   │   ├── google.ts      # ID-token verify wrapper (server)
│   │   │   └── email-otp.ts   # OTP issue + verify (server)
│   │   ├── socket-client.ts   # io(url, { auth: { token } }) singleton + reconnect
│   │   ├── pos/
│   │   │   ├── offline-bridge.ts  # uses window.electron?.sqlite when present
│   │   │   └── …
│   │   ├── prisma-schema.ts · api-spec.ts · srs-content.ts · spec-download.ts
│   │   ├── permissions.ts · permissions-context.tsx
│   │   └── utils.ts
│   │
│   ├── integrations/
│   │   └── supabase/          # AUTO-GENERATED — do not edit
│   │       ├── client.ts
│   │       ├── client.server.ts
│   │       ├── auth-middleware.ts
│   │       ├── auth-attacher.ts
│   │       └── types.ts
│   │
│   ├── hooks/                 # React hooks
│   ├── styles.css             # Design tokens (oklch) + Tailwind v4 theme
│   ├── router.tsx · start.ts · server.ts
│   └── routeTree.gen.ts       # AUTO-GENERATED — do not edit
│
├── supabase/
│   └── config.toml            # Project-level config (do not edit project_id)
├── public/
├── package.json               # Adds bun scripts: electron:dev, electron:build:{win,mac,linux}
├── tsconfig.json
├── vite.config.ts
└── wrangler.jsonc             # Cloudflare Workers config (web only)
`;


const NOTES: { title: string; body: string }[] = [
  { title: "Flat dot-routing", body: "We use TanStack flat naming — admin.companies_.$companyId.tsx not admin/companies/$companyId/index.tsx. Layout files are settings.tsx + settings.profile.tsx with <Outlet /> in the parent. The trailing underscore before $ signals a hidden segment break." },
  { title: "Server functions vs server routes", body: "Internal app logic → createServerFn in *.functions.ts files (typed RPC). External HTTP (webhooks, cron, public APIs) → src/routes/api/public/*.ts file routes with signature verification. Never use Supabase Edge Functions on this stack." },
  { title: "Module boundary", body: "Domain logic lives in src/lib/<domain>. UI lives in src/components or src/routes. Never call Prisma directly from a component — always go through a server function so auth + tenant scoping is enforced." },
  { title: "No NestJS-style modules", body: "TanStack Start is a flat-routes framework. We do NOT add a nest-like controllers/services/dtos triad. The createServerFn + Zod validator + handler trio is our 'controller + dto + service' all in one file." },
  { title: "Generated files", body: "Never edit src/routeTree.gen.ts, src/integrations/supabase/*, or .env. They are regenerated on every build / schema sync. Edits will be silently overwritten." },
  { title: "Where new things go", body: "New domain → src/lib/<domain>/. New page → src/routes/<scope>.<name>.tsx. New shared component → src/components/. New design token → src/styles.css. New server fn → *.functions.ts beside the related domain code." },
  { title: "Stores vs server state", body: "Persistent server data → TanStack Query (queries colocated with server functions). Local UI state (open dialogs, filter state) → useState. Cross-component local state (POS draft, theme) → *-context.tsx or *-store.ts using use-local-storage helper." },
  { title: "POS submodule", body: "src/lib/pos/ holds POS-specific domain logic (auth, branch, menu-data, floorplan-types, storage). src/components/pos/ holds POS-only UI. POS routes live as pos_.<page>.tsx siblings of pos.tsx (the shell). Other parts of the app never import from src/lib/pos directly." },
];

function buildMarkdown(): string {
  const out: string[] = [];
  out.push("# Folder Structure — Salon SaaS");
  out.push("");
  out.push("Canonical module layout. Use this map when deciding where new code belongs.");
  out.push("");
  out.push("```");
  out.push(TREE);
  out.push("```");
  out.push("");
  out.push("## Conventions");
  for (const n of NOTES) {
    out.push(`\n### ${n.title}\n`);
    out.push(n.body);
  }
  return out.join("\n");
}

function FolderStructurePage() {
  const md = buildMarkdown();
  const html = wrapHtml("Folder Structure — Salon SaaS", `<pre style="white-space:pre-wrap">${md.replace(/[&<>]/g, (c) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;" }[c]!))}</pre>`);
  return (
    <div className="mx-auto max-w-5xl px-6 py-10">
      <header className="mb-6 flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="mb-2 inline-flex items-center gap-2 rounded-full border border-emerald-500/30 bg-emerald-500/10 px-3 py-0.5 text-xs font-medium text-emerald-700">specs · structure</div>
          <h1 className="text-3xl font-bold tracking-tight">Folder Structure</h1>
          <p className="mt-2 text-sm text-muted-foreground">Canonical module layout. Use this map when deciding where new code belongs.</p>
        </div>
        <div className="flex flex-wrap gap-2">
          <button onClick={() => downloadBlob("folder-structure.md", md, "text/markdown")} className="rounded-lg bg-primary px-3 py-1.5 text-xs font-medium text-primary-foreground hover:opacity-90">↓ Markdown</button>
          <button onClick={() => downloadBlob("folder-structure.html", html, "text/html")} className="rounded-lg border border-border bg-background px-3 py-1.5 text-xs font-medium hover:bg-muted">↓ HTML</button>
          <button onClick={() => copyText(md)} className="rounded-lg border border-border bg-background px-3 py-1.5 text-xs font-medium hover:bg-muted">⧉ Copy MD</button>
        </div>
      </header>

      <pre className="overflow-auto rounded-xl border border-border bg-[#0b1020] p-5 font-mono text-[12px] leading-relaxed text-slate-100">{TREE}</pre>

      <section className="mt-8 grid gap-3 md:grid-cols-2">
        {NOTES.map((n) => (
          <div key={n.title} className="rounded-xl border border-border bg-card p-4">
            <h3 className="mb-1 text-sm font-semibold">{n.title}</h3>
            <p className="text-xs leading-relaxed text-muted-foreground">{n.body}</p>
          </div>
        ))}
      </section>
    </div>
  );
}
export default routeOptions.component;
